package com.tanlifei.download.entity.test;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "range".
 */
public class RangesEntry {

    private Long id;
    /** Not-null value. */
    private String url;
    private Integer range_key;
    private Integer rangeTotalLength;
    /** Not-null value. */
    private String rangesEntryId;

    public RangesEntry() {
    }

    public RangesEntry(Long id, String url) {
        this.id = id;
        this.url = url;
    }

    public RangesEntry(Long id, String url, Integer range_key, Integer rangeTotalLength, String rangesEntryId) {
        this.id = id;
        this.url = url;
        this.range_key = range_key;
        this.rangeTotalLength = rangeTotalLength;
        this.rangesEntryId = rangesEntryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getRange_key() {
        return range_key;
    }

    public void setRange_key(Integer range_key) {
        this.range_key = range_key;
    }

    public Integer getRangeTotalLength() {
        return rangeTotalLength;
    }

    public void setRangeTotalLength(Integer rangeTotalLength) {
        this.rangeTotalLength = rangeTotalLength;
    }

    /** Not-null value. */
    public String getRangesEntryId() {
        return rangesEntryId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRangesEntryId(String rangesEntryId) {
        this.rangesEntryId = rangesEntryId;
    }

}
